/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as HiringTargetRouteImport } from './routes/hiring/$target'
import { Route as InterviewTargetRouteImport } from './routes/interview/$target'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as ReferralsIndexRouteImport } from './routes/referrals/index'
import { Route as ReferralsReferralIdRouteImport } from './routes/referrals/$referralId'
import { Route as TalentIndexRouteImport } from './routes/talent/index'
import { Route as TalentCandidateIdRouteImport } from './routes/talent/$candidateId'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as JobsJobIdEditRouteImport } from './routes/jobs/$jobId/edit'
import { Route as JobsJobIdPublishedRouteImport } from './routes/jobs/$jobId/published'
import { Route as TalentCandidateIdResumeRouteImport } from './routes/talent/$candidateId/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringTargetRoute = HiringTargetRouteImport.update({
  id: '/hiring/$target',
  path: '/hiring/$target',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTargetRoute = InterviewTargetRouteImport.update({
  id: '/interview/$target',
  path: '/interview/$target',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsReferralIdRoute = ReferralsReferralIdRouteImport.update({
  id: '/referrals/$referralId',
  path: '/referrals/$referralId',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/talent/',
  path: '/talent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentCandidateIdRoute = TalentCandidateIdRouteImport.update({
  id: '/talent/$candidateId',
  path: '/talent/$candidateId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdEditRoute = JobsJobIdEditRouteImport.update({
  id: '/jobs/$jobId/edit',
  path: '/jobs/$jobId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdPublishedRoute = JobsJobIdPublishedRouteImport.update({
  id: '/jobs/$jobId/published',
  path: '/jobs/$jobId/published',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentCandidateIdResumeRoute = TalentCandidateIdResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => TalentCandidateIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/$target': typeof HiringTargetRoute
  '/interview/$target': typeof InterviewTargetRoute
  '/jobs/new': typeof JobsNewRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/talent/$candidateId': typeof TalentCandidateIdRouteWithChildren
  '/jobs/': typeof JobsIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/$jobId/published': typeof JobsJobIdPublishedRoute
  '/talent/$candidateId/resume': typeof TalentCandidateIdResumeRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/$target': typeof HiringTargetRoute
  '/interview/$target': typeof InterviewTargetRoute
  '/jobs/new': typeof JobsNewRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/talent/$candidateId': typeof TalentCandidateIdRouteWithChildren
  '/jobs': typeof JobsIndexRoute
  '/referrals': typeof ReferralsIndexRoute
  '/talent': typeof TalentIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/$jobId/published': typeof JobsJobIdPublishedRoute
  '/talent/$candidateId/resume': typeof TalentCandidateIdResumeRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/forgot': typeof ForgotRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/payments': typeof PaymentsRoute
  '/privacy': typeof PrivacyRoute
  '/reset': typeof ResetRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/$target': typeof HiringTargetRoute
  '/interview/$target': typeof InterviewTargetRoute
  '/jobs/new': typeof JobsNewRoute
  '/referrals/$referralId': typeof ReferralsReferralIdRoute
  '/talent/$candidateId': typeof TalentCandidateIdRouteWithChildren
  '/jobs/': typeof JobsIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/jobs/$jobId/edit': typeof JobsJobIdEditRoute
  '/jobs/$jobId/published': typeof JobsJobIdPublishedRoute
  '/talent/$candidateId/resume': typeof TalentCandidateIdResumeRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/forgot'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/payments'
    | '/privacy'
    | '/reset'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/hiring/$target'
    | '/interview/$target'
    | '/jobs/new'
    | '/referrals/$referralId'
    | '/talent/$candidateId'
    | '/jobs/'
    | '/referrals/'
    | '/talent/'
    | '/jobs/$jobId/edit'
    | '/jobs/$jobId/published'
    | '/talent/$candidateId/resume'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/forgot'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/payments'
    | '/privacy'
    | '/reset'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/hiring/$target'
    | '/interview/$target'
    | '/jobs/new'
    | '/referrals/$referralId'
    | '/talent/$candidateId'
    | '/jobs'
    | '/referrals'
    | '/talent'
    | '/jobs/$jobId/edit'
    | '/jobs/$jobId/published'
    | '/talent/$candidateId/resume'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/forgot'
    | '/help'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/overview'
    | '/payments'
    | '/privacy'
    | '/reset'
    | '/session-expired'
    | '/settings'
    | '/setup'
    | '/signup'
    | '/terms'
    | '/verify'
    | '/welcome'
    | '/hiring/$target'
    | '/interview/$target'
    | '/jobs/new'
    | '/referrals/$referralId'
    | '/talent/$candidateId'
    | '/jobs/'
    | '/referrals/'
    | '/talent/'
    | '/jobs/$jobId/edit'
    | '/jobs/$jobId/published'
    | '/talent/$candidateId/resume'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  ForgotRoute: typeof ForgotRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  PaymentsRoute: typeof PaymentsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetRoute: typeof ResetRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  HiringTargetRoute: typeof HiringTargetRoute
  InterviewTargetRoute: typeof InterviewTargetRoute
  JobsNewRoute: typeof JobsNewRoute
  ReferralsReferralIdRoute: typeof ReferralsReferralIdRoute
  TalentCandidateIdRoute: typeof TalentCandidateIdRouteWithChildren
  JobsIndexRoute: typeof JobsIndexRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
  TalentIndexRoute: typeof TalentIndexRoute
  JobsJobIdEditRoute: typeof JobsJobIdEditRoute
  JobsJobIdPublishedRoute: typeof JobsJobIdPublishedRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/$target': {
      id: '/hiring/$target'
      path: '/hiring/$target'
      fullPath: '/hiring/$target'
      preLoaderRoute: typeof HiringTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$target': {
      id: '/interview/$target'
      path: '/interview/$target'
      fullPath: '/interview/$target'
      preLoaderRoute: typeof InterviewTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/$referralId': {
      id: '/referrals/$referralId'
      path: '/referrals/$referralId'
      fullPath: '/referrals/$referralId'
      preLoaderRoute: typeof ReferralsReferralIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/talent'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$candidateId': {
      id: '/talent/$candidateId'
      path: '/talent/$candidateId'
      fullPath: '/talent/$candidateId'
      preLoaderRoute: typeof TalentCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/edit': {
      id: '/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof JobsJobIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/published': {
      id: '/jobs/$jobId/published'
      path: '/jobs/$jobId/published'
      fullPath: '/jobs/$jobId/published'
      preLoaderRoute: typeof JobsJobIdPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/$candidateId/resume': {
      id: '/talent/$candidateId/resume'
      path: '/resume'
      fullPath: '/talent/$candidateId/resume'
      preLoaderRoute: typeof TalentCandidateIdResumeRouteImport
      parentRoute: typeof TalentCandidateIdRoute
    }
  }
}

interface TalentCandidateIdRouteChildren {
  TalentCandidateIdResumeRoute: typeof TalentCandidateIdResumeRoute
}

const TalentCandidateIdRouteChildren: TalentCandidateIdRouteChildren = {
  TalentCandidateIdResumeRoute: TalentCandidateIdResumeRoute,
}

const TalentCandidateIdRouteWithChildren =
  TalentCandidateIdRoute._addFileChildren(TalentCandidateIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  ForgotRoute: ForgotRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  PaymentsRoute: PaymentsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetRoute: ResetRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  HiringTargetRoute: HiringTargetRoute,
  InterviewTargetRoute: InterviewTargetRoute,
  JobsNewRoute: JobsNewRoute,
  ReferralsReferralIdRoute: ReferralsReferralIdRoute,
  TalentCandidateIdRoute: TalentCandidateIdRouteWithChildren,
  JobsIndexRoute: JobsIndexRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
  TalentIndexRoute: TalentIndexRoute,
  JobsJobIdEditRoute: JobsJobIdEditRoute,
  JobsJobIdPublishedRoute: JobsJobIdPublishedRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
